### ISSUE TITLE
无法刷卡

### ISSUE THREAD

**Issue by Dream-Rainy** [Sanheiii/Mageki#18]
ongeki 1.40使用aimeio后，无法刷卡，test中固件版本和硬件版本为空，刷卡测试一秒后必失败。
主界面会无限自动刷卡并提示
![47ffeb6c04a212eb82a60e7e6624dcd2](https://github.com/Sanheiii/Mageki/assets/88184993/11d72c6a-4b69-4b15-be1a-6960da517886)

segatools.ini如下
```ini
[vfs]
amfs=amfs
option=option
appdata=appdata

[aime]
enable=0
aimePath=DEVICE\aime.txt
felicaGen=0

[dns]
default=192.168.31.117

[netenv]
enable=1

[keychip]
;id=
gameId=SDDT

[pcbid]
; ALLS PCB Serial ID
;serialNo=

[gpio]
; ALLS DIP switches.
enable=1

; Enable freeplay mode. This will disable the coin slot and set the game to
; freeplay. Keep in mind that some game modes (e.g. Freedom/Time Modes) will not
; allow you to start a game in freeplay mode.
freeplay=1

; LAN Install: If multiple machines are present on the same LAN then set 
; this to 1 on exactly one machine and set this to 0 on all others.
dipsw1=1

[gfx]
enable=1

[led15093]
; 837-15093-06 LED board emulation setting.
enable=1

[mu3io]
path=MU3Input.dll

[aimeio]
path=MU3Input.dll

[io4]
; Input API selection for JVS input emulator.
; Test button virtual-key code. Default is the 1 key.
test=0x31
; Service button virtual-key code. Default is the 2 key.
service=0x32
; Keyboard button to increment coin counter. Default is the 3 key.
coin=0x33

; Set "1" to enable mouse lever emulation, "0" to use XInput
mouse=1

; Keyboard input bindings
left1=0x41  ; A
left2=0x53	; S
left3=0x44	; D

leftSide=0x01	; Mouse Left
rightSide=0x02	; Mouse Right

right1=0x4A ; J
right1=0x4B ; K
right3=0x4C	; L

leftMenu=0x55	; U
rightMenu=0x4F	; O
```

**Comment by mxihan** [comment]
你需要将aime部分下的enable设置为1


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sanheiii/Mageki"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月19日(星期一) 中午1:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Sanheiii/Mageki] 无法刷卡 (Issue #18)





 
ongeki 1.40使用aimeio后，无法刷卡，test中固件版本和硬件版本为空，刷卡测试一秒后必失败。
 主界面会无限自动刷卡并提示
 47ffeb6c04a212eb82a60e7e6624dcd2.png (view on web)
 
segatools.ini如下
 [vfs] amfs=amfs option=option appdata=appdata [aime] enable=0 aimePath=DEVICE\aime.txt felicaGen=0 [dns] default=192.168.31.117 [netenv] enable=1 [keychip] ;id= gameId=SDDT [pcbid] ; ALLS PCB Serial ID ;serialNo= [gpio] ; ALLS DIP switches. enable=1 ; Enable freeplay mode. This will disable the coin slot and set the game to ; freeplay. Keep in mind that some game modes (e.g. Freedom/Time Modes) will not ; allow you to start a game in freeplay mode. freeplay=1 ; LAN Install: If multiple machines are present on the same LAN then set  ; this to 1 on exactly one machine and set this to 0 on all others. dipsw1=1 [gfx] enable=1 [led15093] ; 837-15093-06 LED board emulation setting. enable=1 [mu3io] path=MU3Input.dll [aimeio] path=MU3Input.dll [io4] ; Input API selection for JVS input emulator. ; Test button virtual-key code. Default is the 1 key. test=0x31 ; Service button virtual-key code. Default is the 2 key. service=0x32 ; Keyboard button to increment coin counter. Default is the 3 key. coin=0x33 ; Set "1" to enable mouse lever emulation, "0" to use XInput mouse=1 ; Keyboard input bindings left1=0x41  ; A left2=0x53	; S left3=0x44	; D leftSide=0x01	; Mouse Left rightSide=0x02	; Mouse Right right1=0x4A ; J right1=0x4B ; K right3=0x4C	; L leftMenu=0x55	; U rightMenu=0x4F	; O
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;




RIN酱&nbsp;ちゃ
***@***.***
